version: "3"
services:
  db:
    image: postgres:11.1
    network_mode: bridge
    container_name: postgres
    volumes:
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./src/main/resources/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    expose:
      - 5432
    environment:
      - DEBUG=false
      - POSTGRES_USER=guiborges
      - POSTGRES_PASSWORD=gui1234
      - POSTGRES_DB=assistent
    restart: always

#APP
  springbootapp:
    depends_on:
      - db
    links:
      - db
    volumes:
      - postgres-data
      - .:/app
    build:
      .
    ports:
      - 8081:8081
      - 443:443
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=guiborges
      - DATABASE_NAME=assistent
      - DATABASE_PASSWORD=gui1234
      - DATABASE_PORT=5432