version: "3"
services:
  db:
    image: postgres:latest
    container_name: postgres
    volumes:
      - ./src/main/resources/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
    - 5433:5432
    environment:
      - DEBUG=false
      - POSTGRES_USER=guiborges
      - POSTGRES_PASSWORD=gui1234
      - POSTGRES_DB=assistent
    restart: always

#APP
  springbootapp:
    depends_on:
      - db
    links:
      - db
    volumes:
      - postgres-data
    build:
      .
    ports:
      - 8081:8081
    environment:
      - 'spring.datasource.url=jdbc:postgresql://db:5432/assistent'