spring:
  application:
    name: assistent
  datasource:
    #url: jdbc:postgresql://localhost:5432/assistent
    url: jdbc:postgresql://db:5432/assistent?createDatabaseIfNotExist=true&useSSL=false #docker
    username: guiborges
    password: gui1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: secret
server:
  port: 8081