spring:
  application:
    name: assistent
  datasource:
    url: jdbc:postgresql://localhost:5432/assistent
    username: guiborges
    password: gui1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
jwt:
  secret: secret
server:
  port: 8081
